# Teste: vector store para CUIs

In [1]:
import pandas as pd 
import numpy as np
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from tqdm import tqdm
import sys
import os

# Get absolute path to project root
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.insert(0, project_root)

In [2]:
print(f"Project root: {project_root}")

Project root: /home/ia368/projetos/imageclef2026-rag

# Import CUIs

In [3]:
dataset_path = "../../datasets/imageclef/dataset/cui_mapping.csv"

cui_df = pd.read_csv(dataset_path)
cui_df.head()

        CUI                   Canonical name
0  C0016522            Foramen Ovale, Patent
1  C0457846  Cervical segment of spinal cord
2  C0578537               Cavitation of lung
3  C0179751                Epidural catheter
4  C3489393                    Hiatal Hernia

In [10]:
len(cui_df)

1934

In [5]:
cui_2026 = pd.read_csv("../dev_caption/concepts.csv")
cui_2026.head()

,ID,CUIs
0,ImageCLEFmedical_Caption_2026_train_0,C0040405
1,ImageCLEFmedical_Caption_2026_train_1,C1306645;C0817096;C0442800;C0018787;C0242073
2,ImageCLEFmedical_Caption_2026_train_2,C0040405;C0856747
3,ImageCLEFmedical_Caption_2026_train_3,C0041618
4,ImageCLEFmedical_Caption_2026_train_4,C0040405;C0040053

In [6]:
# Tratar coluna CUIs (podem existir múltiplos valores separados por ';')
cui_unique_2026 = sorted({
    cui.strip()
    for cell in cui_2026["CUIs"].dropna().astype(str)
    for cui in cell.split(";")
    if cui.strip()
})

print(f"Total de CUIs únicos: {len(cui_unique_2026)}")
print(f"Exemplo (primeiros 10): {cui_unique_2026[:10]}")

Total de CUIs únicos: 2646
Exemplo (primeiros 10): ['C0000726', 'C0000741', 'C0000833', 'C0000846', 'C0000962', 'C0001074', 'C0001080', 'C0001162', 'C0001168', 'C0001208']

In [ ]:
# todos cui_unique_2026 estao em cui_df['CUI'] ?

if all(cui in cui_df['CUI'].values for cui in cui_unique_2026):
    print("Todos os CUIs únicos de 2026 estão presentes no DataFrame de mapeamento.")
else:
    missing_cuis = [cui for cui in cui_unique_2026 if cui not in cui_df['CUI'].values]
    print(f"Total de CUIs faltantes: {len(missing_cuis)}")
    print(f"CUIs faltantes: {missing_cuis}")

Total de CUIs faltantes: 777
CUIs faltantes: ['C0000741', 'C0001080', 'C0002726', 'C0002760', 'C0002871', 'C0003486', 'C0003490', 'C0003509', 'C0003707', 'C0004031', 'C0004626', 'C0005767', 'C0005898', 'C0005939', 'C0005967', 'C0006111', 'C0006142', 'C0006270', 'C0006382', 'C0006497', 'C0006826', 'C0007113', 'C0007130', 'C0007138', 'C0007194', 'C0007281', 'C0007282', 'C0007572', 'C0007787', 'C0007847', 'C0007873', 'C0008034', 'C0008520', 'C0008827', 'C0009201', 'C0009917', 'C0009995', 'C0010068', 'C0010097', 'C0010276', 'C0010417', 'C0010678', 'C0010964', 'C0011119', 'C0011302', 'C0011325', 'C0011443', 'C0011981', 'C0012634', 'C0014013', 'C0014038', 'C0014520', 'C0014533', 'C0014609', 'C0014850', 'C0014856', 'C0014858', 'C0014866', 'C0015029', 'C0015183', 'C0015388', 'C0015914', 'C0016045', 'C0016109', 'C0016540', 'C0017070', 'C0017145', 'C0017168', 'C0017181', 'C0017525', 'C0017589', 'C0018023', 'C0018220', 'C0018418', 'C0018427', 'C0018784', 'C0018826', 'C0018870', 'C0018934', 'C0018946', 'C0019116', 'C0019163', 'C0019310', 'C0019326', 'C0019558', 'C0019560', 'C0019655', 'C0019829', 'C0020224', 'C0020538', 'C0020614', 'C0021376', 'C0021843', 'C0022116', 'C0022417', 'C0022658', 'C0022889', 'C0023869', 'C0023895', 'C0024109', 'C0024141', 'C0024296', 'C0024449', 'C0024796', 'C0025289', 'C0025344', 'C0025465', 'C0025473', 'C0025500', 'C0026277', 'C0026946', 'C0026975', 'C0027858', 'C0028882', 'C0029127', 'C0029134', 'C0029434', 'C0029463', 'C0029965', 'C0030353', 'C0031022', 'C0031038', 'C0031046', 'C0031048', 'C0031090', 'C0031144', 'C0032008', 'C0032231', 'C0032266', 'C0032290', 'C0032717', 'C0032984', 'C0033270', 'C0034090', 'C0034215', 'C0034885', 'C0034910', 'C0035067', 'C0035085', 'C0035322', 'C0035353', 'C0035877', 'C0035878', 'C0036421', 'C0036846', 'C0037941', 'C0038013', 'C0038246', 'C0038539', 'C0038826', 'C0038828', 'C0039433', 'C0039441', 'C0040046', 'C0040124', 'C0040136', 'C0040147', 'C0040186', 'C0040395', 'C0040442', 'C0041343', 'C0041428', 'C0041445', 'C0041602', 'C0041915', 'C0042031', 'C0042134', 'C0042138', 'C0042173', 'C0042341', 'C0042373', 'C0042448', 'C0042909', 'C0042993', 'C0043356', 'C0079218', 'C0079744', 'C0085232', 'C0085413', 'C0085648', 'C0149516', 'C0149562', 'C0149579', 'C0149782', 'C0149825', 'C0149863', 'C0149955', 'C0150595', 'C0150683', 'C0151465', 'C0151603', 'C0151664', 'C0151744', 'C0151945', 'C0152018', 'C0152101', 'C0152244', 'C0152299', 'C0152320', 'C0152322', 'C0152327', 'C0152336', 'C0152381', 'C0152427', 'C0152445', 'C0153676', 'C0153678', 'C0155676', 'C0155909', 'C0156156', 'C0156290', 'C0156369', 'C0158360', 'C0158371', 'C0158634', 'C0162406', 'C0162475', 'C0162870', 'C0175751', 'C0178879', 'C0179760', 'C0179781', 'C0179799', 'C0182092', 'C0182215', 'C0183062', 'C0183517', 'C0183663', 'C0183975', 'C0203668', 'C0205224', 'C0205237', 'C0205241', 'C0205318', 'C0205350', 'C0205358', 'C0205364', 'C0205378', 'C0205406', 'C0205416', 'C0205617', 'C0205618', 'C0205699', 'C0206061', 'C0206069', 'C0206329', 'C0206330', 'C0206698', 'C0206754', 'C0220654', 'C0221065', 'C0221093', 'C0221227', 'C0221230', 'C0221248', 'C0221725', 'C0221757', 'C0222608', 'C0222661', 'C0222665', 'C0222694', 'C0222745', 'C0222760', 'C0222787', 'C0223170', 'C0223492', 'C0223533', 'C0223598', 'C0223605', 'C0223608', 'C0223616', 'C0223670', 'C0223686', 'C0223717', 'C0223733', 'C0223932', 'C0224146', 'C0224159', 'C0224231', 'C0224252', 'C0224302', 'C0224306', 'C0224384', 'C0224388', 'C0224416', 'C0224423', 'C0224427', 'C0224435', 'C0224449', 'C0224453', 'C0224463', 'C0224473', 'C0224549', 'C0224577', 'C0224794', 'C0224853', 'C0225043', 'C0225064', 'C0225166', 'C0225206', 'C0225219', 'C0225266', 'C0225269', 'C0225273', 'C0225295', 'C0225298', 'C0225357', 'C0225425', 'C0225432', 'C0225460', 'C0225461', 'C0225536', 'C0225569', 'C0225593', 'C0225641', 'C0225701', 'C0225832', 'C0225920', 'C0225929', 'C0225988', 'C0226019', 'C0226025', 'C0226045', 'C0226091', 'C0226104', 'C0226147', 'C0226247', 'C0226309', 'C0226310', 'C0226331', 'C0226335', 'C0226371', 'C0226406', 'C0226411', 'C0226416', 'C0226417', 'C0226447', 'C0226476', 'C0226504', 'C0226513', 'C0226633', 'C0226654', 'C0226686', 'C0226730', 'C0226754', 'C0226778', 'C0226787', 'C0226791', 'C0226863', 'C0226920', 'C0227029', 'C0227048', 'C0227054', 'C0227149', 'C0227192', 'C0227265', 'C0227282', 'C0227299', 'C0227348', 'C0227543', 'C0227573', 'C0227690', 'C0227701', 'C0227710', 'C0227736', 'C0227792', 'C0227793', 'C0227822', 'C0227979', 'C0228150', 'C0228188', 'C0228269', 'C0228325', 'C0228398', 'C0228467', 'C0228878', 'C0228885', 'C0228912', 'C0228959', 'C0229095', 'C0229116', 'C0229210', 'C0229217', 'C0229218', 'C0229298', 'C0229299', 'C0229353', 'C0229665', 'C0229667', 'C0229754', 'C0229867', 'C0229868', 'C0229966', 'C0230003', 'C0230015', 'C0230041', 'C0230059', 'C0230073', 'C0230120', 'C0230138', 'C0230165', 'C0230181', 'C0230184', 'C0230195', 'C0230203', 'C0230245', 'C0230283', 'C0230285', 'C0230403', 'C0230429', 'C0230463', 'C0230473', 'C0232353', 'C0232490', 'C0233568', 'C0234108', 'C0234226', 'C0234557', 'C0235328', 'C0235884', 'C0235982', 'C0236033', 'C0236178', 'C0238047', 'C0238124', 'C0238154', 'C0238212', 'C0238434', 'C0238441', 'C0238457', 'C0241961', 'C0242379', 'C0242403', 'C0242490', 'C0242690', 'C0243001', 'C0259770', 'C0262537', 'C0263833', 'C0263907', 'C0264069', 'C0264497', 'C0264499', 'C0264550', 'C0264734', 'C0265357', 'C0265700', 'C0265783', 'C0265886', 'C0265950', 'C0266025', 'C0266200', 'C0266270', 'C0266328', 'C0266389', 'C0266464', 'C0266470', 'C0266989', 'C0267467', 'C0267548', 'C0267869', 'C0267898', 'C0267947', 'C0268000', 'C0268203', 'C0268407', 'C0268842', 'C0269102', 'C0269185', 'C0270680', 'C0270774', 'C0270777', 'C0271476', 'C0272414', 'C0272416', 'C0278460', 'C0280131', 'C0281839', 'C0281936', 'C0282193', 'C0302144', 'C0302148', 'C0311420', 'C0311438', 'C0332156', 'C0332250', 'C0332442', 'C0332524', 'C0332529', 'C0332534', 'C0332567', 'C0332906', 'C0332966', 'C0333113', 'C0333133', 'C0333157', 'C0333169', 'C0333277', 'C0333307', 'C0333404', 'C0333549', 'C0333596', 'C0333629', 'C0334044', 'C0334121', 'C0334150', 'C0334163', 'C0336574', 'C0338573', 'C0340062', 'C0340279', 'C0340704', 'C0341698', 'C0344730', 'C0344925', 'C0345950', 'C0346205', 'C0346306', 'C0346989', 'C0347631', 'C0347634', 'C0347646', 'C0348070', 'C0370199', 'C0376154', 'C0376710', 'C0393956', 'C0403447', 'C0403477', 'C0405469', 'C0428791', 'C0431384', 'C0439850', 'C0442158', 'C0442192', 'C0442603', 'C0443149', 'C0443215', 'C0443278', 'C0443304', 'C0444070', 'C0444575', 'C0445106', 'C0446421', 'C0446423', 'C0446424', 'C0446425', 'C0446427', 'C0446429', 'C0446433', 'C0446559', 'C0447050', 'C0447132', 'C0447304', 'C0447562', 'C0447661', 'C0447801', 'C0448042', 'C0448192', 'C0448637', 'C0448660', 'C0450102', 'C0450964', 'C0450965', 'C0451641', 'C0451899', 'C0453910', 'C0456480', 'C0456938', 'C0457432', 'C0457523', 'C0458351', 'C0458394', 'C0458580', 'C0458583', 'C0458703', 'C0459559', 'C0459697', 'C0459928', 'C0459929', 'C0459933', 'C0459941', 'C0459957', 'C0460025', 'C0460149', 'C0472377', 'C0475022', 'C0475370', 'C0475433', 'C0475728', 'C0478664', 'C0486616', 'C0494165', 'C0500531', 'C0520562', 'C0520575', 'C0520720', 'C0520866', 'C0520912', 'C0521110', 'C0521158', 'C0521533', 'C0521618', 'C0522562', 'C0522670', 'C0524812', 'C0546256', 'C0549145', 'C0553656', 'C0555895', 'C0558362', 'C0559287', 'C0559359', 'C0559522', 'C0559884', 'C0580863', 'C0581385', 'C0582124', 'C0582240', 'C0582797', 'C0582818', 'C0584895', 'C0585104', 'C0585105', 'C0588195', 'C0595620', 'C0595944', 'C0597984', 'C0598801', 'C0677542', 'C0684550', 'C0686904', 'C0687568', 'C0694549', 'C0694637', 'C0702122', 'C0702176', 'C0729441', 'C0729728', 'C0729907', 'C0730169', 'C0730608', 'C0747635', 'C0749155', 'C0751533', 'C0752244', 'C0840564', 'C0850458', 'C0856761', 'C0872084', 'C0876998', 'C0879615', 'C0920367', 'C0921292', 'C0929301', 'C0935602', 'C0936236', 'C0948441', 'C0949691', 'C1116455', 'C1148523', 'C1185785', 'C1261100', 'C1261120', 'C1264047', 'C1264108', 'C1264124', 'C1265602', 'C1265766', 'C1265808', 'C1266119', 'C1266909', 'C1268198', 'C1268229', 'C1269775', 'C1272681', 'C1272694', 'C1273723', 'C1275506', 'C1278799', 'C1279385', 'C1282006', 'C1282007', 'C1283260', 'C1283566', 'C1283683', 'C1289790', 'C1289793', 'C1290385', 'C1299533', 'C1299890', 'C1301369', 'C1301771', 'C1301827', 'C1302234', 'C1305600', 'C1305601', 'C1305602', 'C1305608', 'C1305727', 'C1305744', 'C1305907', 'C1306871', 'C1321581', 'C1322293', 'C1328248', 'C1368021', 'C1384497', 'C1384670', 'C1412002', 'C1443972', 'C1444748', 'C1456333', 'C1458155', 'C1510665', 'C1511746', 'C1512936', 'C1517559', 'C1522407', 'C1527311', 'C1563019', 'C1568363', 'C1608329', 'C1609519', 'C1621382', 'C1621895', 'C1621958', 'C1688623', 'C1704275', 'C1704356', 'C1709868', 'C1744565', 'C1761592', 'C1879828', 'C1947920', 'C1956110', 'C1997972', 'C2051831', 'C2239176', 'C2350019', 'C2607832', 'C2733158', 'C2919848', 'C2931822', 'C2936258', 'C2938959', 'C2945603', 'C3160858', 'C3165062', 'C3249881', 'C3266676', 'C3266689', 'C3275276', 'C3495801', 'C3536741', 'C3543005', 'C3665420', 'C3714557', 'C3714581', 'C3853547', 'C3854304', 'C3854373', 'C3887486', 'C3887653', 'C4319771', 'C4510374', 'C4510788', 'C4521596', 'C4521765', 'C4551649', 'C4551691', 'C4706712', 'C4706713', 'C5392833', 'C5395152', 'C5441863', 'C5441966']

# Gerar embeddings para CUIs

In [4]:
# Carregar utilitários do projeto
from utils.f_utils import load_config, load_models

In [5]:
# Carregar configuração e modelo MedSigLip
config_path = "../configs/IC2024_valid_emb.yaml"
config = load_config(config_path)

processor, model, device = load_models(config, device='cuda')
print(f"Using device: {device}")
print(f"Model loaded: {config['medsiglip']['model']}")

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

Using device: cuda
Model loaded: google/medsiglip-448

In [6]:
# Dataset para processar apenas textos (Canonical names)
class TextOnlyDataset(Dataset):
    def __init__(self, texts, processor, max_length=64):
        """
        texts: lista de textos (Canonical names)
        processor: processor do MedSigLip
        max_length: tamanho máximo do texto
        """
        self.texts = texts
        self.processor = processor
        self.max_length = max_length
    
    def __len__(self):
        return len(self.texts)
    
    def __getitem__(self, idx):
        text = self.texts[idx]
        
        # Processar apenas o texto (sem imagem)
        encoding = self.processor(
            text=text,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )
        
        # Remove batch dimension
        encoding = {k: v.squeeze(0) for k, v in encoding.items()}
        return encoding

In [7]:
# Função para gerar embeddings de texto
def generate_text_embeddings(model, dataloader, device):
    """
    Gera embeddings apenas para textos usando o encoder de texto do MedSigLip
    """
    model.eval()
    model.to(device)
    
    all_text_embeds = []
    
    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Generating text embeddings"):
            batch = {k: v.to(device) for k, v in batch.items()}
            
            # Gerar embeddings de texto
            text_embeds = model.get_text_features(
                input_ids=batch["input_ids"]
            )
            
            # Normalização (para cosine similarity)
            text_embeds = text_embeds / text_embeds.norm(dim=-1, keepdim=True)
            
            all_text_embeds.append(text_embeds.cpu())
    
    all_text_embeds = torch.cat(all_text_embeds, dim=0)
    return all_text_embeds

In [8]:
# Preparar dados: extrair Canonical names
canonical_names = cui_df['Canonical name'].tolist()

print(f"Total de Canonical names: {len(canonical_names)}")
print(f"Exemplo: {canonical_names[0]}")

Total de Canonical names: 1934
Exemplo: Foramen Ovale, Patent

In [9]:
# Criar dataset e dataloader
text_dataset = TextOnlyDataset(
    texts=canonical_names,
    processor=processor,
    max_length=64
)

text_dataloader = DataLoader(
    text_dataset,
    batch_size=32,
    shuffle=False,
    pin_memory=True
)

print(f"Dataset criado com {len(text_dataset)} amostras")
print(f"Número de batches: {len(text_dataloader)}")

Dataset criado com 1934 amostras
Número de batches: 61

In [ ]:
# Gerar embeddings
cui_text_embeddings = generate_text_embeddings(
    model=model,
    dataloader=text_dataloader,
    device=device
)

print(f"\n✅ Embeddings gerados com sucesso!")
print(f"📊 Shape dos embeddings: {cui_text_embeddings.shape}")
print(f"📊 Tipo: {type(cui_text_embeddings)}")

In [ ]:
# Salvar embeddings (opcional)
output_dir = "../artifacts/embeddings"
os.makedirs(output_dir, exist_ok=True)

torch.save(cui_text_embeddings, os.path.join(output_dir, "cui_canonical_names_embeddings.pt"))
torch.save(canonical_names, os.path.join(output_dir, "cui_canonical_names.pt"))

print(f"✅ Embeddings salvos em {output_dir}")
print(f"📄 Arquivo de embeddings: cui_canonical_names_embeddings.pt")
print(f"📄 Arquivo de nomes: cui_canonical_names.pt")